### ISSUE TITLE
Scorecard badge is down

### ISSUE THREAD

**Issue by PierreDemailly** [dashlog/core#43]
[![OpenSSF
Scorecard](https://api.securityscorecards.dev/projects/github.com/dashlog/core/badge?style=for-the-badge)]
instead of 
[![OpenSSF
Scorecard](https://api.securityscorecards.dev/projects/github.com/dashlog/core/badge?style=for-the-badge)](https://api.securityscorecards.dev/projects/github.com/dashlog/core)

(need to add link, you can click on the badge to see it)

**Comment by SebasRomero** [comment]
The badge isn't working?
